# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
    - r: release
      os: linux
      dist: trusty
      sudo: false
    - r: release
      os: osx
